[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "randomly"
authors = [{name = "Dimitry Zub", email = "dimitryzub@gmail.com"}]
dependencies = ["flit_core >=3.3.0"]
requires-python = ">=3.6"
readme = "README.md"
version = "0.1.0"
dynamic = ["version", "description"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.optional-dependencies]
test = [
    "pytest >=6.2.5",
    "pytest-randomly==3.10.1",
]


[project.urls]
Home = "https://github.com/dimitryzub/randomly"
