name: Testing randomit CI workflow
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Upload with coverage to randomit"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
      - name: Run tests and collect coverage
        run: |
          pytest --cov=./ --cov-report=xml
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2